<?php

namespace Database\Seeders;
use App\Models\Branch\ThanaOrUpazila;
use Illuminate\Database\Seeder;

class UpazilaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            ['district_id' => '1', 'thana_or_upazila_name' => 'Amtali', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '1', 'thana_or_upazila_name' => 'Bamna', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '1', 'thana_or_upazila_name' => 'Barguna-S', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '1', 'thana_or_upazila_name' => 'Betagi', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '1', 'thana_or_upazila_name' => 'Patharghata', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '1', 'thana_or_upazila_name' => 'Taltali', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '2', 'thana_or_upazila_name' => 'Agailjhara', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '2', 'thana_or_upazila_name' => 'Babuganj', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '2', 'thana_or_upazila_name' => 'Bakerganj', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '2', 'thana_or_upazila_name' => 'Banaripara', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '2', 'thana_or_upazila_name' => 'Barishal-S', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '2', 'thana_or_upazila_name' => 'Gouranadi', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '2', 'thana_or_upazila_name' => 'Hizla', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '2', 'thana_or_upazila_name' => 'Hizla', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '2', 'thana_or_upazila_name' => 'Hizla', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '2', 'thana_or_upazila_name' => 'Uzirpur', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '3', 'thana_or_upazila_name' => 'Bhola-S', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '3', 'thana_or_upazila_name' => 'Borhanuddin', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '3', 'thana_or_upazila_name' => 'Charfassion', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '3', 'thana_or_upazila_name' => 'Daulatkhan', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '3', 'thana_or_upazila_name' => 'Lalmohan', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '3', 'thana_or_upazila_name' => 'Monpura', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '3', 'thana_or_upazila_name' => 'Tazumuddin', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '4', 'thana_or_upazila_name' => 'Jhalokathi-S', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '4', 'thana_or_upazila_name' => 'Kathalia', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '4', 'thana_or_upazila_name' => 'Kathalia', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '4', 'thana_or_upazila_name' => 'Rajapur', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '5', 'thana_or_upazila_name' => 'Bauphal', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '5', 'thana_or_upazila_name' => 'Dashmina', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '5', 'thana_or_upazila_name' => 'Dashmina', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '5', 'thana_or_upazila_name' => 'Galachipa', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '5', 'thana_or_upazila_name' => 'Galachipa', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '5', 'thana_or_upazila_name' => 'Mirjaganj', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '5', 'thana_or_upazila_name' => 'Patuakhali-S', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '5', 'thana_or_upazila_name' => 'Rangabali', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '6', 'thana_or_upazila_name' => 'Bhandaria', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '6', 'thana_or_upazila_name' => 'Kawkhali', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '6', 'thana_or_upazila_name' => 'Kawkhali', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '6', 'thana_or_upazila_name' => 'Nazirpur', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '6', 'thana_or_upazila_name' => 'Nesarabad', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '6', 'thana_or_upazila_name' => 'Pirojpur-S', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '6', 'thana_or_upazila_name' => 'Zianagar', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '8', 'thana_or_upazila_name' => 'Akhaura', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '8', 'thana_or_upazila_name' => 'Ashuganj', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '8', 'thana_or_upazila_name' => 'Brahmanbaria-S', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '8', 'thana_or_upazila_name' => 'Bancharampur', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '8', 'thana_or_upazila_name' => 'Bijoynagar', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '8', 'thana_or_upazila_name' => 'Kasba', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '8', 'thana_or_upazila_name' => 'Nabinagar', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '8', 'thana_or_upazila_name' => 'Nasirnagar', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '8', 'thana_or_upazila_name' => 'Sarail', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '7', 'thana_or_upazila_name' => 'Alikadam', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '7', 'thana_or_upazila_name' => 'Bandarban-S', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '7', 'thana_or_upazila_name' => 'Lama', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '7', 'thana_or_upazila_name' => 'Naikhyongchari', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '7', 'thana_or_upazila_name' => 'Rowangchari', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '7', 'thana_or_upazila_name' => 'Ruma', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '7', 'thana_or_upazila_name' => 'Thanchi', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '9', 'thana_or_upazila_name' => 'Chandpur-S', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '9', 'thana_or_upazila_name' => 'Faridganj', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '9', 'thana_or_upazila_name' => 'Haimchar', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '9', 'thana_or_upazila_name' => 'Haziganj', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '9', 'thana_or_upazila_name' => 'Kachua', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '9', 'thana_or_upazila_name' => 'Matlab (Dakshin)', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '9', 'thana_or_upazila_name' => 'Matlab (Uttar)', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '9', 'thana_or_upazila_name' => 'Shahrasti', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '10', 'thana_or_upazila_name' => 'Anwara', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '10', 'thana_or_upazila_name' => 'Banskhali', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '10', 'thana_or_upazila_name' => 'Boalkhali', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '10', 'thana_or_upazila_name' => 'Chandanish', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '10', 'thana_or_upazila_name' => 'Fatikchari', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '10', 'thana_or_upazila_name' => 'Hathazari', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '10', 'thana_or_upazila_name' => 'Karnaphuli', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '10', 'thana_or_upazila_name' => 'Lohagara', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '10', 'thana_or_upazila_name' => 'Mirsharai', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '10', 'thana_or_upazila_name' => 'Patiya', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '10', 'thana_or_upazila_name' => 'Rangunia', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '10', 'thana_or_upazila_name' => 'Raojan', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '10', 'thana_or_upazila_name' => 'Sandwip', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '10', 'thana_or_upazila_name' => 'Satkania', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '10', 'thana_or_upazila_name' => 'Sitakunda', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => "12", 'thana_or_upazila_name' => 'Chakoria', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => "12", 'thana_or_upazila_name' => "Cox's Bazar-S", 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => "12", 'thana_or_upazila_name' => 'Kutubdia', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => "12", 'thana_or_upazila_name' => 'Moheskhali', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => "12", 'thana_or_upazila_name' => 'Pekua', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => "12", 'thana_or_upazila_name' => 'Ramu', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => "12", 'thana_or_upazila_name' => 'Teknaf', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => "12", 'thana_or_upazila_name' => 'Ukhiya', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '11', 'thana_or_upazila_name' => 'Barura', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '11', 'thana_or_upazila_name' => 'Brahmanpara', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '11', 'thana_or_upazila_name' => 'Burichong', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '11', 'thana_or_upazila_name' => 'Chandina', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '11', 'thana_or_upazila_name' => 'Chouddagram', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '11', 'thana_or_upazila_name' => 'Cumilla-S', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '11', 'thana_or_upazila_name' => 'Cumilla-S Daksin', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '11', 'thana_or_upazila_name' => 'Daudkandi', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '11', 'thana_or_upazila_name' => 'Debidwar', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '11', 'thana_or_upazila_name' => 'Homna', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '11', 'thana_or_upazila_name' => 'Laksham', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '11', 'thana_or_upazila_name' => 'Lalmai', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '11', 'thana_or_upazila_name' => 'Meghna', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '11', 'thana_or_upazila_name' => 'Monohorganj', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '11', 'thana_or_upazila_name' => 'Muradnagar', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '11', 'thana_or_upazila_name' => 'Nangalkot', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '11', 'thana_or_upazila_name' => 'Titas', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '13', 'thana_or_upazila_name' => 'Chhagalniya', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '13', 'thana_or_upazila_name' => 'Daganbhuiyan', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '13', 'thana_or_upazila_name' => 'Feni-S', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '13', 'thana_or_upazila_name' => 'Fulgazi', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '13', 'thana_or_upazila_name' => 'Porshuram', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '13', 'thana_or_upazila_name' => 'Sonagazi', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '14', 'thana_or_upazila_name' => 'Dighinala', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '14', 'thana_or_upazila_name' => 'Guimara', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '14', 'thana_or_upazila_name' => 'Khagrachari-S', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '14', 'thana_or_upazila_name' => 'Laxmichari', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '14', 'thana_or_upazila_name' => 'Mahalchari', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '14', 'thana_or_upazila_name' => 'Manikchari', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '14', 'thana_or_upazila_name' => 'Matiranga', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '14', 'thana_or_upazila_name' => 'Panchari', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '14', 'thana_or_upazila_name' => 'Ramgarh', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '15', 'thana_or_upazila_name' => 'Komol Nagar', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '15', 'thana_or_upazila_name' => 'Laxmipur-S', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '15', 'thana_or_upazila_name' => 'Raipur', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '15', 'thana_or_upazila_name' => 'Ramganj', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '15', 'thana_or_upazila_name' => 'Ramgati', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '16', 'thana_or_upazila_name' => 'Begumganj', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '16', 'thana_or_upazila_name' => 'Chatkhil', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '16', 'thana_or_upazila_name' => 'Companiganj', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '16', 'thana_or_upazila_name' => 'Hatiya', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '16', 'thana_or_upazila_name' => 'Kabir Hat', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '16', 'thana_or_upazila_name' => 'Noakhali-S', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '16', 'thana_or_upazila_name' => 'Senbag', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '16', 'thana_or_upazila_name' => 'Sonaimuri', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '16', 'thana_or_upazila_name' => 'Subarna Char', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '17', 'thana_or_upazila_name' => 'Baghaichari', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '17', 'thana_or_upazila_name' => 'Barkal', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '17', 'thana_or_upazila_name' => 'Belaichari', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '17', 'thana_or_upazila_name' => 'Juraichari', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '17', 'thana_or_upazila_name' => 'Kaptai', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '17', 'thana_or_upazila_name' => 'Kaukhali', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '17', 'thana_or_upazila_name' => 'Langadu', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '17', 'thana_or_upazila_name' => 'Nanniarchar', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '17', 'thana_or_upazila_name' => 'Rajosthali', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '17', 'thana_or_upazila_name' => 'Rangamati-S', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '18', 'thana_or_upazila_name' => 'Dhamrai Upazila', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '18', 'thana_or_upazila_name' => 'Dohar Upazila', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '18', 'thana_or_upazila_name' => 'Keraniganj Upazila', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '18', 'thana_or_upazila_name' => 'Nawabganj Upazila', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '18', 'thana_or_upazila_name' => 'Savar Upazila', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '18', 'thana_or_upazila_name' => 'Adabar Thana', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '18', 'thana_or_upazila_name' => 'Badda Thana', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '18', 'thana_or_upazila_name' => 'Bangsal Thana', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '18', 'thana_or_upazila_name' => 'Bhashantek Thana', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '18', 'thana_or_upazila_name' => 'Cantonment Thana', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '18', 'thana_or_upazila_name' => 'Chowkbazar Thana', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '18', 'thana_or_upazila_name' => 'Darus Salam Thana', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '18', 'thana_or_upazila_name' => 'Demra Thana', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '18', 'thana_or_upazila_name' => 'Dhanmondi Thana', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '18', 'thana_or_upazila_name' => 'Gendaria Thana', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '18', 'thana_or_upazila_name' => 'Gulshan Thana', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '18', 'thana_or_upazila_name' => 'Bangsal Thana', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '18', 'thana_or_upazila_name' => 'Hatirjheel Thana', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '18', 'thana_or_upazila_name' => 'Hazaribagh Thana', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '18', 'thana_or_upazila_name' => 'Jatrabari Thana', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '18', 'thana_or_upazila_name' => 'Kadamtali Thana', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '18', 'thana_or_upazila_name' => 'Kafrul Thana', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '18', 'thana_or_upazila_name' => 'Kalabagan Thana', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '18', 'thana_or_upazila_name' => 'Kamrangirchar Thana', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '18', 'thana_or_upazila_name' => 'Khilgaon Thana', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '18', 'thana_or_upazila_name' => 'Khilkhet Thana', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '18', 'thana_or_upazila_name' => 'Kotwali Thana (Dhaka)', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '18', 'thana_or_upazila_name' => 'Lalbagh Thana', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '18', 'thana_or_upazila_name' => 'Mirpur Model Thana', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '18', 'thana_or_upazila_name' => 'Mohammadpur Thana', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '18', 'thana_or_upazila_name' => 'Motijheel Thana', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '18', 'thana_or_upazila_name' => 'Mugda Thana', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '18', 'thana_or_upazila_name' => 'New Market Thana', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '18', 'thana_or_upazila_name' => 'Pallabi Thana', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '18', 'thana_or_upazila_name' => 'Paltan Thana', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '18', 'thana_or_upazila_name' => 'Ramna Thana', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '18', 'thana_or_upazila_name' => 'Rampura Thana', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '18', 'thana_or_upazila_name' => 'Sabujbagh Thana', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '18', 'thana_or_upazila_name' => 'Shah Ali Thana', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '18', 'thana_or_upazila_name' => 'Shahbag Thana', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '18', 'thana_or_upazila_name' => 'Shahjahanpur Thana', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '18', 'thana_or_upazila_name' => 'Sher-e-Bangla Nagar Thana', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '18', 'thana_or_upazila_name' => 'Shyampur Thana', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '18', 'thana_or_upazila_name' => 'Sutrapur Thana', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '18', 'thana_or_upazila_name' => 'Tejgaon Industrial Area Thana', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '18', 'thana_or_upazila_name' => 'Tejgaon Thana', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '18', 'thana_or_upazila_name' => 'Turag Thana', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '18', 'thana_or_upazila_name' => 'Uttara East Thana', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '18', 'thana_or_upazila_name' => 'Vatara Thana', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '18', 'thana_or_upazila_name' => 'Wari Thana', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '19', 'thana_or_upazila_name' => 'Alfadanga', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '19', 'thana_or_upazila_name' => 'Bhanga', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '19', 'thana_or_upazila_name' => 'Boalmari', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '19', 'thana_or_upazila_name' => 'Charbhadrasan', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '19', 'thana_or_upazila_name' => 'Faridpur-S', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '19', 'thana_or_upazila_name' => 'Madhukhali', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '19', 'thana_or_upazila_name' => 'Nagarkanda', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '19', 'thana_or_upazila_name' => 'Sadarpur', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '19', 'thana_or_upazila_name' => 'Saltha', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '20', 'thana_or_upazila_name' => 'Gazipur-S', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '20', 'thana_or_upazila_name' => 'Kaliakoir', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '20', 'thana_or_upazila_name' => 'Kaliganj', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '20', 'thana_or_upazila_name' => 'Kapasia', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '20', 'thana_or_upazila_name' => 'Sreepur', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '21', 'thana_or_upazila_name' => 'Kasiani', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '21', 'thana_or_upazila_name' => 'Kotwalipara', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '21', 'thana_or_upazila_name' => 'Muksudpur', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '21', 'thana_or_upazila_name' => 'Tungipara', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '21', 'thana_or_upazila_name' => 'Gopalganj-S', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '22', 'thana_or_upazila_name' => 'Austagram', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '22', 'thana_or_upazila_name' => 'Bajitpur', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '22', 'thana_or_upazila_name' => 'Bhairab', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '22', 'thana_or_upazila_name' => 'Hossainpur', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '22', 'thana_or_upazila_name' => 'Itna', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '22', 'thana_or_upazila_name' => 'Karimganj', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '22', 'thana_or_upazila_name' => 'Katiadi', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '22', 'thana_or_upazila_name' => 'Kishoreganj-S', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '22', 'thana_or_upazila_name' => 'Kuliarchar', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '22', 'thana_or_upazila_name' => 'Mithamoin', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '22', 'thana_or_upazila_name' => 'Nikli', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '22', 'thana_or_upazila_name' => 'Pakundia', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '22', 'thana_or_upazila_name' => 'Tarail', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '23', 'thana_or_upazila_name' => 'Kalkini', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '23', 'thana_or_upazila_name' => 'Madaripur-S', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '23', 'thana_or_upazila_name' => 'Rajoir', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '23', 'thana_or_upazila_name' => 'Shibchar', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '24', 'thana_or_upazila_name' => 'Daulatpur', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '24', 'thana_or_upazila_name' => 'Ghior', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '24', 'thana_or_upazila_name' => 'Harirampur', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '24', 'thana_or_upazila_name' => 'Manikganj-S', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '24', 'thana_or_upazila_name' => 'Saturia', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '24', 'thana_or_upazila_name' => 'Shivalaya', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '24', 'thana_or_upazila_name' => 'Singair', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '25', 'thana_or_upazila_name' => 'Gazaria', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '25', 'thana_or_upazila_name' => 'Lauhajong', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '25', 'thana_or_upazila_name' => 'Munshiganj-S', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '25', 'thana_or_upazila_name' => 'Sirajdikhan', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '25', 'thana_or_upazila_name' => 'Sreenagar', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '25', 'thana_or_upazila_name' => 'Sreenagar', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '26', 'thana_or_upazila_name' => 'Araihazar', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '26', 'thana_or_upazila_name' => 'Bandar', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '26', 'thana_or_upazila_name' => 'Narayanganj-S', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '26', 'thana_or_upazila_name' => 'Rupganj', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '26', 'thana_or_upazila_name' => 'Sonargaon', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '27', 'thana_or_upazila_name' => 'Belabo', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '27', 'thana_or_upazila_name' => 'Monohardi', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '27', 'thana_or_upazila_name' => 'Narshingdi-S', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '27', 'thana_or_upazila_name' => 'Palash', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '27', 'thana_or_upazila_name' => 'Raipura', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '27', 'thana_or_upazila_name' => 'Shibpur', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '28', 'thana_or_upazila_name' => 'Baliakandi', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '28', 'thana_or_upazila_name' => 'Goalanda', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '28', 'thana_or_upazila_name' => 'Kalukhali', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '28', 'thana_or_upazila_name' => 'Pangsha', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '28', 'thana_or_upazila_name' => 'Rajbari-S', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '29', 'thana_or_upazila_name' => 'Bhedarganj', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '29', 'thana_or_upazila_name' => 'Damuddya', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '29', 'thana_or_upazila_name' => 'Goshairhat', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '29', 'thana_or_upazila_name' => 'Janjira', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '29', 'thana_or_upazila_name' => 'Naria', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '29', 'thana_or_upazila_name' => 'Shariatpur-S', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '30', 'thana_or_upazila_name' => 'Basail', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '30', 'thana_or_upazila_name' => 'Bhuapur', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '30', 'thana_or_upazila_name' => 'Delduar', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '30', 'thana_or_upazila_name' => 'Dhanbari', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '30', 'thana_or_upazila_name' => 'Ghatail', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '30', 'thana_or_upazila_name' => 'Gopalpur', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '30', 'thana_or_upazila_name' => 'Kalihati', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '30', 'thana_or_upazila_name' => 'Madhupur', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '30', 'thana_or_upazila_name' => 'Mirzapur', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '30', 'thana_or_upazila_name' => 'Nagarpur', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '30', 'thana_or_upazila_name' => 'Shakhipur', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '30', 'thana_or_upazila_name' => 'Tangail-S', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '35', 'thana_or_upazila_name' => 'Bagerhat-S', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '35', 'thana_or_upazila_name' => 'Chitalmari', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '35', 'thana_or_upazila_name' => 'Fakirhat', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '35', 'thana_or_upazila_name' => 'Kachua', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '35', 'thana_or_upazila_name' => 'Mollahat', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '35', 'thana_or_upazila_name' => 'Mongla', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '35', 'thana_or_upazila_name' => 'Morrelganj', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '35', 'thana_or_upazila_name' => 'Rampal', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '35', 'thana_or_upazila_name' => 'Sharankhola', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '36', 'thana_or_upazila_name' => 'Alamdanga', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '36', 'thana_or_upazila_name' => 'Chuadanga-S', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '36', 'thana_or_upazila_name' => 'Damurhuda', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '36', 'thana_or_upazila_name' => 'Jibannagar', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '37', 'thana_or_upazila_name' => 'Abhoynagar', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '37', 'thana_or_upazila_name' => 'Bagherpara', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '37', 'thana_or_upazila_name' => 'Chowgacha', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '37', 'thana_or_upazila_name' => 'Jashore-S', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '37', 'thana_or_upazila_name' => 'Jhikargacha', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '37', 'thana_or_upazila_name' => 'Keshabpur', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '37', 'thana_or_upazila_name' => 'Monirampur', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '37', 'thana_or_upazila_name' => 'Sarsha', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '38', 'thana_or_upazila_name' => 'Harinakunda', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '38', 'thana_or_upazila_name' => 'Jhenaidah-S', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '38', 'thana_or_upazila_name' => 'Kaliganj', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '38', 'thana_or_upazila_name' => 'KotChandpur', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '38', 'thana_or_upazila_name' => 'Moheshpur', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '38', 'thana_or_upazila_name' => 'Shailkupa', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '39', 'thana_or_upazila_name' => 'Batiaghata', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '39', 'thana_or_upazila_name' => 'Dacope', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '39', 'thana_or_upazila_name' => 'Dighalia', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '39', 'thana_or_upazila_name' => 'Dumuria', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '39', 'thana_or_upazila_name' => 'Koira', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '39', 'thana_or_upazila_name' => 'Paikgacha', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '39', 'thana_or_upazila_name' => 'Phultala', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '39', 'thana_or_upazila_name' => 'Rupsa', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '39', 'thana_or_upazila_name' => 'Terokhada', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '40', 'thana_or_upazila_name' => 'Bheramara', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '40', 'thana_or_upazila_name' => 'Daulatpur', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '40', 'thana_or_upazila_name' => 'Khoksha', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '40', 'thana_or_upazila_name' => 'Kumarkhali', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '40', 'thana_or_upazila_name' => 'Kushtia-S', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '40', 'thana_or_upazila_name' => 'Mirpur', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '41', 'thana_or_upazila_name' => 'Magura-S', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '41', 'thana_or_upazila_name' => 'Mohammadpur', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '41', 'thana_or_upazila_name' => 'Salikha', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '41', 'thana_or_upazila_name' => 'Sreepur', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '42', 'thana_or_upazila_name' => 'Gangni', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '42', 'thana_or_upazila_name' => 'Meherpur-S', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '42', 'thana_or_upazila_name' => 'Mujib Nagar', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '43', 'thana_or_upazila_name' => 'Kalia', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '43', 'thana_or_upazila_name' => 'Lohagara', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '43', 'thana_or_upazila_name' => 'Narail-S', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '44', 'thana_or_upazila_name' => 'Assasuni', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '44', 'thana_or_upazila_name' => 'Debhata', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '44', 'thana_or_upazila_name' => 'Kalaroa', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '44', 'thana_or_upazila_name' => 'Kaliganj', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '44', 'thana_or_upazila_name' => 'Satkhira-S', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '44', 'thana_or_upazila_name' => 'Shyamnagar', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '44', 'thana_or_upazila_name' => 'Tala', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '31', 'thana_or_upazila_name' => 'Bakshiganj', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '31', 'thana_or_upazila_name' => 'Dewanganj', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '31', 'thana_or_upazila_name' => 'Islampur', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '31', 'thana_or_upazila_name' => 'Jamalpur-S', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '31', 'thana_or_upazila_name' => 'Madarganj', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '31', 'thana_or_upazila_name' => 'Melendah', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '31', 'thana_or_upazila_name' => 'Sarishabari', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '32', 'thana_or_upazila_name' => 'Bhaluka', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '32', 'thana_or_upazila_name' => 'Dhobaura', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '32', 'thana_or_upazila_name' => 'Fulbaria', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '32', 'thana_or_upazila_name' => 'Gaffargaon', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '32', 'thana_or_upazila_name' => 'Gouripur', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '32', 'thana_or_upazila_name' => 'Haluaghat', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '32', 'thana_or_upazila_name' => 'Ishwarganj', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '32', 'thana_or_upazila_name' => 'Muktagacha', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '32', 'thana_or_upazila_name' => 'Mymensingh-S', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '32', 'thana_or_upazila_name' => 'Nandail', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '32', 'thana_or_upazila_name' => 'Phulpur', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '32', 'thana_or_upazila_name' => 'Tarakanda', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '32', 'thana_or_upazila_name' => 'Trishal', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '33', 'thana_or_upazila_name' => 'Atpara', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '33', 'thana_or_upazila_name' => 'Barhatta', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '33', 'thana_or_upazila_name' => 'Durgapur', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '33', 'thana_or_upazila_name' => 'Kalmakanda', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '33', 'thana_or_upazila_name' => 'Kendua', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '33', 'thana_or_upazila_name' => 'Khaliajuri', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '33', 'thana_or_upazila_name' => 'Khaliajuri', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '33', 'thana_or_upazila_name' => 'Mohanganj', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '33', 'thana_or_upazila_name' => 'Netrakona-S', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '33', 'thana_or_upazila_name' => 'Purbadhala', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '34', 'thana_or_upazila_name' => 'Jhenaigati', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '34', 'thana_or_upazila_name' => 'Nakla', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '34', 'thana_or_upazila_name' => 'Nalitabari', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '34', 'thana_or_upazila_name' => 'Sherpur-S', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '34', 'thana_or_upazila_name' => 'Sreebordi', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '45', 'thana_or_upazila_name' => 'Adamdighi', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '45', 'thana_or_upazila_name' => 'Bogura-S', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '45', 'thana_or_upazila_name' => 'Dhunot', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '45', 'thana_or_upazila_name' => 'Dhupchancia', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '45', 'thana_or_upazila_name' => 'Gabtali', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '45', 'thana_or_upazila_name' => 'Kahaloo', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '45', 'thana_or_upazila_name' => 'Nandigram', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '45', 'thana_or_upazila_name' => 'Sariakandi', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '45', 'thana_or_upazila_name' => 'Shajahanpur', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '45', 'thana_or_upazila_name' => 'Sherpur', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '45', 'thana_or_upazila_name' => 'Shibganj', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '45', 'thana_or_upazila_name' => 'Sonatala', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '49', 'thana_or_upazila_name' => 'Bholahat', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '49', 'thana_or_upazila_name' => 'Gomostapur', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '49', 'thana_or_upazila_name' => 'Nachol', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '49', 'thana_or_upazila_name' => 'Nawabganj-S', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '49', 'thana_or_upazila_name' => 'Shibganj', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '46', 'thana_or_upazila_name' => 'Akkelpur', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '46', 'thana_or_upazila_name' => 'Joypurhat-S', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '46', 'thana_or_upazila_name' => 'Kalai', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '46', 'thana_or_upazila_name' => 'Khetlal', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '46', 'thana_or_upazila_name' => 'Panchbibi', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '47', 'thana_or_upazila_name' => 'Atrai', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '47', 'thana_or_upazila_name' => 'Badalgachi', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '47', 'thana_or_upazila_name' => 'Dhamoirhat', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '47', 'thana_or_upazila_name' => 'Manda', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '47', 'thana_or_upazila_name' => 'Mohadevpur', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '47', 'thana_or_upazila_name' => 'Naogaon-S', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '47', 'thana_or_upazila_name' => 'Niamatpur', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '47', 'thana_or_upazila_name' => 'Patnitala', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '47', 'thana_or_upazila_name' => 'Porsha', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '47', 'thana_or_upazila_name' => 'Raninagar', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '47', 'thana_or_upazila_name' => 'Shapahar', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '48', 'thana_or_upazila_name' => 'Bagatipara', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '48', 'thana_or_upazila_name' => 'Baraigram', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '48', 'thana_or_upazila_name' => 'Gurudaspur', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '48', 'thana_or_upazila_name' => 'Lalpur', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '48', 'thana_or_upazila_name' => 'Naldanga', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '48', 'thana_or_upazila_name' => 'Natore-S', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '48', 'thana_or_upazila_name' => 'Singra', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '50', 'thana_or_upazila_name' => 'Atghoria', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '50', 'thana_or_upazila_name' => 'Bera', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '50', 'thana_or_upazila_name' => 'Bhangura', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '50', 'thana_or_upazila_name' => 'Chatmohar', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '50', 'thana_or_upazila_name' => 'Faridpur', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '50', 'thana_or_upazila_name' => 'Ishwardi', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '50', 'thana_or_upazila_name' => 'Pabna-S', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '50', 'thana_or_upazila_name' => 'Santhia', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '50', 'thana_or_upazila_name' => 'Sujanagar', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '51', 'thana_or_upazila_name' => 'Bagha', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '51', 'thana_or_upazila_name' => 'Bagmara', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '51', 'thana_or_upazila_name' => 'Charghat', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '51', 'thana_or_upazila_name' => 'Durgapur', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '51', 'thana_or_upazila_name' => 'Rajshahi-S', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '51', 'thana_or_upazila_name' => 'Godagari', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '51', 'thana_or_upazila_name' => 'Mohanpur', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '51', 'thana_or_upazila_name' => 'Paba', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '51', 'thana_or_upazila_name' => 'Puthia', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '51', 'thana_or_upazila_name' => 'Tanore', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '52', 'thana_or_upazila_name' => 'Belkuchi', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '52', 'thana_or_upazila_name' => 'Chowhali', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '52', 'thana_or_upazila_name' => 'Kamarkhand', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '52', 'thana_or_upazila_name' => 'Kazipur', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '52', 'thana_or_upazila_name' => 'Raiganj', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '52', 'thana_or_upazila_name' => 'Shahzadpur', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '52', 'thana_or_upazila_name' => 'Sirajganj-S', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '52', 'thana_or_upazila_name' => 'Tarash', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '52', 'thana_or_upazila_name' => 'Ullapara', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '58', 'thana_or_upazila_name' => 'Birampur', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '58', 'thana_or_upazila_name' => 'Birganj', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '58', 'thana_or_upazila_name' => 'Birol', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '58', 'thana_or_upazila_name' => 'Bochaganj', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '58', 'thana_or_upazila_name' => 'Chirirbandar', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '58', 'thana_or_upazila_name' => 'Dinajpur-S', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '58', 'thana_or_upazila_name' => 'Fulbari', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '58', 'thana_or_upazila_name' => 'Ghoraghat', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '58', 'thana_or_upazila_name' => 'Hakimpur', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '58', 'thana_or_upazila_name' => 'Kaharol', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '58', 'thana_or_upazila_name' => 'Khanshama', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '58', 'thana_or_upazila_name' => 'Nawabganj', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '58', 'thana_or_upazila_name' => 'Parbatipur', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '54', 'thana_or_upazila_name' => 'Fulchari', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '54', 'thana_or_upazila_name' => 'Gaibandha-S', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '54', 'thana_or_upazila_name' => 'Gobindaganj', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '54', 'thana_or_upazila_name' => 'Palashbari', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '54', 'thana_or_upazila_name' => 'Sadullapur', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '54', 'thana_or_upazila_name' => 'Saghata', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '54', 'thana_or_upazila_name' => 'Sundarganj', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '55', 'thana_or_upazila_name' => 'Bhurungamari', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '55', 'thana_or_upazila_name' => 'Chilmari', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '55', 'thana_or_upazila_name' => 'Fulbari', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '55', 'thana_or_upazila_name' => 'Kurigram-S', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '55', 'thana_or_upazila_name' => 'Nageswari', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '55', 'thana_or_upazila_name' => 'Rajarhat', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '55', 'thana_or_upazila_name' => 'Rajibpur', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '55', 'thana_or_upazila_name' => 'Rowmari', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '55', 'thana_or_upazila_name' => 'Ulipur', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '57', 'thana_or_upazila_name' => 'Aditmari', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '57', 'thana_or_upazila_name' => 'Hatibandha', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '57', 'thana_or_upazila_name' => 'Kaliganj', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '57', 'thana_or_upazila_name' => 'Lalmonirhat-S', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '57', 'thana_or_upazila_name' => 'Patgram', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '56', 'thana_or_upazila_name' => 'Dimla', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '56', 'thana_or_upazila_name' => 'Domar', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '56', 'thana_or_upazila_name' => 'Jal18', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '56', 'thana_or_upazila_name' => 'Kishoreganj', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '56', 'thana_or_upazila_name' => 'Nilphamari-S', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '56', 'thana_or_upazila_name' => 'Sayedpur', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '60', 'thana_or_upazila_name' => 'Atwari', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '60', 'thana_or_upazila_name' => 'Boda', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '60', 'thana_or_upazila_name' => 'Debiganj', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '60', 'thana_or_upazila_name' => 'Panchagarh-S', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '60', 'thana_or_upazila_name' => 'Tetulia', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '53', 'thana_or_upazila_name' => 'Badarganj', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '53', 'thana_or_upazila_name' => 'Gangachara', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '53', 'thana_or_upazila_name' => 'Kaunia', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '53', 'thana_or_upazila_name' => 'Mithapukur', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '53', 'thana_or_upazila_name' => 'Pirgacha', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '53', 'thana_or_upazila_name' => 'Pirganj', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '53', 'thana_or_upazila_name' => 'Rangpur-S', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '53', 'thana_or_upazila_name' => 'Taraganj', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '59', 'thana_or_upazila_name' => 'Baliadangi', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '59', 'thana_or_upazila_name' => 'Haripur', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '59', 'thana_or_upazila_name' => 'Pirganj', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '59', 'thana_or_upazila_name' => 'Ranisankail', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '59', 'thana_or_upazila_name' => 'Thakurgaon-S', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '61', 'thana_or_upazila_name' => 'Azmiriganj', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '61', 'thana_or_upazila_name' => 'Bahubal', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '61', 'thana_or_upazila_name' => 'Baniachong', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '61', 'thana_or_upazila_name' => 'Chunarughat', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '61', 'thana_or_upazila_name' => 'Habiganj-S', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '61', 'thana_or_upazila_name' => 'Lakhai', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '61', 'thana_or_upazila_name' => 'Madhabpur', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '61', 'thana_or_upazila_name' => 'Nabiganj', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '61', 'thana_or_upazila_name' => 'Sayestaganj', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '62', 'thana_or_upazila_name' => 'Barlekha', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '62', 'thana_or_upazila_name' => 'Juri', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '62', 'thana_or_upazila_name' => 'Kamalganj', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '62', 'thana_or_upazila_name' => 'Kulaura', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '62', 'thana_or_upazila_name' => 'Moulvibazar-S', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '62', 'thana_or_upazila_name' => 'Rajnagar', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '62', 'thana_or_upazila_name' => 'Sreemangal', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '63', 'thana_or_upazila_name' => 'Biswamvarpur', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '63', 'thana_or_upazila_name' => 'Chatak', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '63', 'thana_or_upazila_name' => 'Dakhin Sunamganj', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '63', 'thana_or_upazila_name' => 'Derai', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '63', 'thana_or_upazila_name' => 'Dharmapasha', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '63', 'thana_or_upazila_name' => 'Doarabazar', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '63', 'thana_or_upazila_name' => 'Jagannathpur', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '63', 'thana_or_upazila_name' => 'Jamalganj', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '63', 'thana_or_upazila_name' => 'Sulla', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '63', 'thana_or_upazila_name' => 'Sunamganj-S', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '63', 'thana_or_upazila_name' => 'Tahirpur', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '64', 'thana_or_upazila_name' => 'Balaganj', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '64', 'thana_or_upazila_name' => 'Beanibazar', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '64', 'thana_or_upazila_name' => 'Biswanath', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '64', 'thana_or_upazila_name' => 'Companiganj', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '64', 'thana_or_upazila_name' => 'Dakshin Surma', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '64', 'thana_or_upazila_name' => 'Fenchuganj', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '64', 'thana_or_upazila_name' => 'Golapganj', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '64', 'thana_or_upazila_name' => 'Gowainghat', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '64', 'thana_or_upazila_name' => 'Jointiapur', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '64', 'thana_or_upazila_name' => 'Kanaighat', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '64', 'thana_or_upazila_name' => 'Osmaninagar', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '64', 'thana_or_upazila_name' => 'Sylhet-S', 'created_at' => now(), 'updated_at' => now()],
            ['district_id' => '64', 'thana_or_upazila_name' => 'Zakiganj', 'created_at' => now(), 'updated_at' => now()],

        ];

        // Use insert to add multiple records [ use the command : php artisan db:seed --class=EmailVerificationSeeder]
        ThanaOrUpazila::insert($data);
    }
}
